/// Flutter icons Custom
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Custom
///      fonts:
///       - asset: fonts/Custom.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class Custom {
  Custom._();

  static const _kFontFam = 'Custom';

  static const IconData ic_bar = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData ic_bom = const IconData(0xe801, fontFamily: _kFontFam);
  static const IconData ic_check = const IconData(0xe802, fontFamily: _kFontFam);
  static const IconData ic_logo = const IconData(0xe803, fontFamily: _kFontFam);
  static const IconData ic_ruim = const IconData(0xe804, fontFamily: _kFontFam);
}
